# -*- coding: utf-8 -*-
"""
Batch Convert Z-Score CSVs to Real Power (Watts)

Reads all CSV files in created_data/UK_DALE/ (generated by multivariate_ukdale_preprocess.py),
converts Aggregate and Appliance columns from Z-score to Watts, and saves with _realPower suffix.

Normalization Constants (from multivariate_ukdale_preprocess.py):
  Aggregate: Mean=400, Std=500
  Appliances: Per params_appliance dict
"""

import pandas as pd
import numpy as np
import os
import glob
from pathlib import Path

# Constants used in GENERATION (multivariate_ukdale_preprocess.py)
AGG_MEAN = 400
AGG_STD = 500

APPLIANCE_SPECS = {
    'kettle': {'mean': 700, 'std': 1000},
    'microwave': {'mean': 500, 'std': 800},
    'fridge': {'mean': 200, 'std': 400},
    'dishwasher': {'mean': 700, 'std': 1000},
    'washingmachine': {'mean': 400, 'std': 700}
}

INPUT_DIR = 'created_data/UK_DALE'

def convert_to_watts(df, appliance_name):
    """Convert Z-score dataframe to Watts in place"""
    
    # Check if this is a multivariate file (>= 10 cols)
    if len(df.columns) < 2:
        print("  [Skipping] Too few columns")
        return None
        
    print(f"  Converting {appliance_name}...")
    
    # 1. Convert Aggregate (Col 0)
    # z = (x - mean) / std  =>  x = z * std + mean
    df.iloc[:, 0] = df.iloc[:, 0] * AGG_STD + AGG_MEAN
    
    # 2. Convert Appliance (Col 1)
    if appliance_name in APPLIANCE_SPECS:
        specs = APPLIANCE_SPECS[appliance_name]
        mean = specs['mean']
        std = specs['std']
        df.iloc[:, 1] = df.iloc[:, 1] * std + mean
    else:
        print(f"  [Warning] Unknown appliance '{appliance_name}', skipping appliance column conversion")
        
    # 3. Clip negative values (Logic from mixing script)
    df.iloc[:, 0] = df.iloc[:, 0].clip(lower=0)
    df.iloc[:, 1] = df.iloc[:, 1].clip(lower=0)
    
    return df

def main():
    print(f"=== Batch Converting Z-Score to Real Power ===")
    print(f"Directory: {INPUT_DIR}")
    print(f"Constants: Agg Mean={AGG_MEAN}, Agg Std={AGG_STD}")
    
    # Find all CSVs
    csv_files = glob.glob(os.path.join(INPUT_DIR, "*.csv"))
    
    count = 0
    for file_path in csv_files:
        filename = os.path.basename(file_path)
        
        # Skip already converted files
        if "_realPower" in filename:
            continue
            
        # Identify appliance
        appliance_found = None
        for app in APPLIANCE_SPECS.keys():
            if app in filename:
                appliance_found = app
                break
        
        if not appliance_found:
            print(f"Skipping {filename}: Could not detect appliance name")
            continue
            
        print(f"\nProcessing: {filename} (Appliance: {appliance_found})")
        
        try:
            # Read CSV
            df = pd.read_csv(file_path)
            
            # Convert
            df_watts = convert_to_watts(df, appliance_found)
            
            if df_watts is not None:
                # Save
                new_filename = filename.replace(".csv", "_realPower.csv")
                output_path = os.path.join(INPUT_DIR, new_filename)
                
                df_watts.to_csv(output_path, index=False)
                print(f"  Saved to: {new_filename}")
                count += 1
                
        except Exception as e:
            print(f"  Error processing {filename}: {e}")

    print(f"\n=== Completed ===")
    print(f"Converted {count} files.")

if __name__ == "__main__":
    main()
