# -*- coding: utf-8 -*-
"""
Batch Convert Z-Score CSVs to Real Power (Watts)

Reads all CSV files in created_data/UK_DALE/ (generated by multivariate_ukdale_preprocess.py),
converts Aggregate and Appliance columns from Z-score to Watts, and saves with _realPower suffix.

Normalization Constants (from multivariate_ukdale_preprocess.py):
  Aggregate: Mean=400, Std=500
  Appliances: Per params_appliance dict
"""

import pandas as pd
import numpy as np
import os
import glob
from pathlib import Path

# Constants used in GENERATION (multivariate_ukdale_preprocess.py)
# Constants matched with real_power_visualize.py / ukdale_processing.py
AGG_MEAN = 522
AGG_STD = 814

APPLIANCE_SPECS = {
    'kettle': {'mean': 700, 'std': 1000, 'max_power': 3998},
    'microwave': {'mean': 500, 'std': 800, 'max_power': 2000},
    'fridge': {'mean': 200, 'std': 400, 'max_power': 350},
    'dishwasher': {'mean': 700, 'std': 1000, 'max_power': 3964},
    'washingmachine': {'mean': 400, 'std': 700, 'max_power': 3999}
}

INPUT_DIR = 'created_data/UK_DALE'

def convert_to_watts(df, appliance_name):
    """Convert Z-score dataframe to Watts in place"""
    
    # Check for empty or invalid dataframe
    if df.empty:
        return None
        
    print(f"  Converting {appliance_name}...")
    
    # Identify columns based on names or indices
    cols = df.columns
    
    # 1. Convert Aggregate
    # Try logical names first, then fall back to index 0
    agg_col = None
    if 'aggregate' in cols:
        agg_col = 'aggregate'
    elif '0' in cols: # String '0' from CSV read
        agg_col = '0'
    elif len(cols) > 0:
        agg_col = cols[0] # Assume first column is aggregate
        
    if agg_col:
        print(f"    - Aggregate column: {agg_col}")
        # z = (x - mean) / std  =>  x = z * std + mean
        df[agg_col] = df[agg_col] * AGG_STD + AGG_MEAN
        df[agg_col] = df[agg_col].clip(lower=0)
    
    # 2. Convert Appliance
    # Try logical names first, then fall back to index 1
    app_col = None
    if appliance_name in cols:
        app_col = appliance_name
    elif 'appliance' in cols:
        app_col = 'appliance'
    elif '1' in cols:
        app_col = '1'
    elif len(cols) > 1:
        app_col = cols[1] # Assume second column is appliance
        
    if app_col and appliance_name in APPLIANCE_SPECS:
        print(f"    - Appliance column: {app_col}")
        specs = APPLIANCE_SPECS[appliance_name]
        mean = specs['mean']
        std = specs['std']
        df[app_col] = df[app_col] * std + mean
        df[app_col] = df[app_col].clip(lower=0)
    else:
        print(f"  [Warning] Unknown appliance column or specs for '{appliance_name}', skipping appliance conversion")

    # Time features (columns 2-9 usually) are left as is (sin/cos encoding)
    
    return df

def main():
    print(f"=== Batch Converting Z-Score to Real Power ===")
    print(f"Directory: {INPUT_DIR}")
    print(f"Constants: Agg Mean={AGG_MEAN}, Agg Std={AGG_STD}")
    
    # Find all CSVs
    csv_files = glob.glob(os.path.join(INPUT_DIR, "*.csv"))
    
    count = 0
    for file_path in csv_files:
        filename = os.path.basename(file_path)
        
        # Skip already converted files
        if "_realPower" in filename:
            continue
            
        # Identify appliance
        appliance_found = None
        for app in APPLIANCE_SPECS.keys():
            if app in filename:
                appliance_found = app
                break
        
        if not appliance_found:
            print(f"Skipping {filename}: Could not detect appliance name")
            continue
            
        print(f"\nProcessing: {filename} (Appliance: {appliance_found})")
        
        try:
            # Read CSV
            df = pd.read_csv(file_path)
            
            # Convert
            df_watts = convert_to_watts(df, appliance_found)
            
            if df_watts is not None:
                # Save
                new_filename = filename.replace(".csv", "_realPower.csv")
                output_path = os.path.join(INPUT_DIR, new_filename)
                
                df_watts.to_csv(output_path, index=False)
                print(f"  Saved to: {new_filename}")
                count += 1
                
        except Exception as e:
            print(f"  Error processing {filename}: {e}")

    print(f"\n=== Completed ===")
    print(f"Converted {count} files.")

if __name__ == "__main__":
    main()
