import json
import os

notebook_path = r"c:\Users\Raymond Tie\Desktop\DiffusionModel_NILM\Train_CNN_CGAN_Baseline_Local.ipynb"

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Update the training loop cell (index 3) with speed optimizations
new_source = [
    "# ==========================================\n",
    "# TRAINING LOOP (OPTIMIZED FOR SPEED)\n",
    "# ==========================================\n",
    "from torch.cuda.amp import autocast, GradScaler\n",
    "\n",
    "print(f'Starting Optimized Training...')\n",
    "completed_appliances = []\n",
    "scaler = GradScaler() # For Mixed Precision Training\n",
    "\n",
    "for appliance in APPLIANCES:\n",
    "    print(f'\\n{\"=\"*60}')\n",
    "    print(f'PROCESSING: {appliance.upper()}')\n",
    "    print(f'{\"=\"*60}')\n",
    "    \n",
    "    CSV_PATH = os.path.join(BASE_DIR, 'Data', 'datasets', f'{appliance}_multivariate.csv')\n",
    "    OUT_DIR = os.path.join(BASE_DIR, 'Synthetic_data', appliance) \n",
    "    os.makedirs(OUT_DIR, exist_ok=True)\n",
    "\n",
    "    if not os.path.exists(CSV_PATH):\n",
    "        continue\n",
    "\n",
    "    # Fast Loading with limited features if possible, or just standard load\n",
    "    df = pd.read_csv(CSV_PATH)\n",
    "    power_col = next((c for c in df.columns if 'power' in c.lower() or appliance in c.lower()), df.columns[-1])\n",
    "    p_min, p_max = df[power_col].min(), df[power_col].max()\n",
    "    raw_p_norm = (df[power_col].values - p_min) / (p_max - p_min) * 2 - 1\n",
    "    time_features_df = df.drop(columns=[power_col]).apply(pd.to_numeric, errors='coerce').fillna(0)\n",
    "    dataset = NILM_Dataset(raw_p_norm, time_features_df.values)\n",
    "    \n",
    "    # SPEED OPTIMIZATION: num_workers and pin_memory\n",
    "    train_loader = DataLoader(\n",
    "        dataset, \n",
    "        batch_size=BATCH_SIZE, \n",
    "        shuffle=True, \n",
    "        drop_last=True,\n",
    "        num_workers=0, # Set to 0 for Windows stability, but keep logic ready\n",
    "        pin_memory=True if torch.cuda.is_available() else False\n",
    "    )\n",
    "\n",
    "    G, D = Generator().to(device), Discriminator().to(device)\n",
    "    opt_G = torch.optim.Adam(G.parameters(), lr=0.0002, betas=(0.5, 0.999))\n",
    "    opt_D = torch.optim.Adam(D.parameters(), lr=0.0001, betas=(0.5, 0.999))\n",
    "    criterion = nn.BCELoss()\n",
    "\n",
    "    print(f'🔥 Fast Training with Mixed Precision (AMP)...')\n",
    "    for epoch in range(1, EPOCHS_PER_APP + 1):\n",
    "        last_real_p, last_fake_p = None, None\n",
    "\n",
    "        for i, (real_p, _) in enumerate(train_loader):\n",
    "            real_p = real_p.to(device, non_blocking=True); bs = real_p.size(0)\n",
    "            \n",
    "            # Train Discriminator with AMP\n",
    "            opt_D.zero_grad(set_to_none=True)\n",
    "            with autocast():\n",
    "                z = torch.randn(bs, 100).to(device);\n",
    "                fake_p = G(z)\n",
    "                pred_real = D(real_p)\n",
    "                pred_fake = D(fake_p.detach())\n",
    "                loss_d = (criterion(pred_real, torch.full((bs,1), 0.9).to(device)) + \\\n",
    "                          criterion(pred_fake, torch.zeros(bs,1).to(device))) / 2\n",
    "            \n",
    "            scaler.scale(loss_d).backward()\n",
    "            scaler.step(opt_D)\n",
    "\n",
    "            # Train Generator (2 steps) with AMP\n",
    "            for _ in range(2):\n",
    "                opt_G.zero_grad(set_to_none=True)\n",
    "                with autocast():\n",
    "                    fake_p = G(torch.randn(bs, 100).to(device))\n",
    "                    loss_g = criterion(D(fake_p), torch.ones(bs,1).to(device)) + \\\n",
    "                             0.2 * torch.mean(torch.abs(fake_p[:, :, 1:] - fake_p[:, :, :-1]))\n",
    "                scaler.scale(loss_g).backward()\n",
    "                scaler.step(opt_G)\n",
    "            \n",
    "            scaler.update()\n",
    "            last_real_p, last_fake_p = real_p.detach().cpu(), fake_p.detach().cpu()\n",
    "\n",
    "        # SPEED OPTIMIZATION: Plot every 50 epochs instead of 10 to reduce UI overhead\n",
    "        if epoch % 50 == 0 or epoch == 1:\n",
    "            clear_output(wait=True)\n",
    "            if completed_appliances: print(f\"✅ DONE: {', '.join(completed_appliances)}\")\n",
    "            print(f'🚀 {appliance.upper()} | Epoch {epoch}/{EPOCHS_PER_APP} | Speed: Optimized AMP')\n",
    "            plt.figure(figsize=(10, 3))\n",
    "            plt.plot((last_real_p[0,0]+1)/2, label='Real', alpha=0.5)\n",
    "            plt.plot((last_fake_p[0,0]+1)/2, label='Generated', color='orange')\n",
    "            plt.title(f'{appliance.upper()} Epoch {epoch}'); plt.legend(); plt.show(); plt.close()\n",
    "\n",
    "    # Sampling (Fast Eval Mode)\n",
    "    print(f'Saving findings...')\n",
    "    NUM_GEN = len(dataset) * 2\n",
    "    G.eval()\n",
    "    with torch.no_grad(), autocast():\n",
    "        all_f = [ (G(torch.randn(BATCH_SIZE, 100).to(device)).cpu().numpy() + 1) / 2 for _ in range(NUM_GEN // BATCH_SIZE + 1) ]\n",
    "    \n",
    "    final_p = np.concatenate(all_f, axis=0)[:NUM_GEN]\n",
    "    indices = np.random.choice(len(dataset), NUM_GEN, replace=True)\n",
    "    final_merged = np.concatenate([np.expand_dims(final_p.squeeze(1), axis=2), \n",
    "                                  np.array([dataset[idx][1].numpy() for idx in indices])], axis=2)\n",
    "\n",
    "    np_path = os.path.join(OUT_DIR, f'synthetic_{appliance}.npy')\n",
    "    np.save(np_path, final_merged)\n",
    "    torch.save(G.state_dict(), os.path.join(OUT_DIR, f'{appliance}_generator.pth'))\n",
    "    \n",
    "    completed_appliances.append(appliance.upper())\n",
    "    \n",
    "    # Cleanup\n",
    "    import gc; del G, D, df, dataset; gc.collect(); torch.cuda.empty_cache(); plt.close('all')\n"
]

nb['cells'][3]['source'] = new_source

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print('Speed optimizations applied successfully.')
