"""
Visualization Script for Synthetic Data
This script visualizes the quality of washing machine power data generated by the diffusion model.

Usage:
    python visualize_synthetic_data.py --appliance washingmachine
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import os

def load_synthetic_data(appliance_name):
    """Load synthetic data for comparison"""
    fake_data_path = f'OUTPUT/{appliance_name}_512/ddpm_fake_{appliance_name}_512.npy'
    
    if not os.path.exists(fake_data_path):
        print(f"ERROR: Synthetic data file not found: {fake_data_path}")
        print(f"   Please run sampling command first:")
        print(f"   python main.py --config Config/{appliance_name}.yaml --name {appliance_name}_512 --milestone 10")
        return None
    
    fake_data = np.load(fake_data_path)
    print(f"Loaded synthetic data: {fake_data_path}")
    print(f"   Data shape: {fake_data.shape}")
    print(f"   Number of samples: {len(fake_data)}")
    print(f"   Sequence length: {fake_data.shape[1]}")
    
    return fake_data

def load_real_data(appliance_name):
    """Load real data for comparison"""
    real_data_path = f'Data/datasets/{appliance_name}.csv'
    
    if not os.path.exists(real_data_path):
        print(f"WARNING: Real data file not found: {real_data_path}")
        print(f"   Will only display synthetic data")
        return None
    
    df = pd.read_csv(real_data_path)
    real_data = df['power'].values
    print(f"Loaded real data: {real_data_path}")
    print(f"   Data length: {len(real_data)}")
    
    return real_data

def plot_visualization(fake_data, real_data=None, appliance_name='appliance'):
    """Create 4 visualization charts"""
    
    # Flatten data
    fake_flat = fake_data.flatten()
    
    # Create plots
    if real_data is not None:
        fig, axes = plt.subplots(2, 2, figsize=(16, 10))
        fig.suptitle(f'Synthetic Data Quality Assessment - {appliance_name.upper()}', 
                     fontsize=16, fontweight='bold')
    else:
        fig, axes = plt.subplots(2, 2, figsize=(16, 10))
        fig.suptitle(f'Synthetic Data Visualization - {appliance_name.upper()}', 
                     fontsize=16, fontweight='bold')
    
    # ===== Chart 1: Time Series Comparison (First 5000 points) =====
    ax1 = axes[0, 0]
    sample_size = min(5000, len(fake_flat))
    
    if real_data is not None:
        real_sample = min(5000, len(real_data))
        ax1.plot(fake_flat[:sample_size], color='blue', linewidth=0.8, 
                alpha=0.7, label='Synthetic Data')
        ax1.plot(real_data[:real_sample], color='red', linewidth=0.8, 
                alpha=0.7, label='Real Data')
        ax1.set_title('Time Series Comparison (First 5000 Samples)', fontweight='bold')
    else:
        ax1.plot(fake_flat[:sample_size], color='blue', linewidth=0.8, alpha=0.7)
        ax1.set_title('Synthetic Data Time Series (First 5000 Samples)', fontweight='bold')
    
    ax1.set_xlabel('Time Index')
    ax1.set_ylabel('Power (normalized)')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # ===== Chart 2: Synthetic Data Detail View =====
    ax2 = axes[0, 1]
    start_idx = 10000
    end_idx = min(15000, len(fake_flat))
    ax2.plot(range(start_idx, end_idx), fake_flat[start_idx:end_idx], 
            color='green', linewidth=1.0)
    ax2.set_title(f'Synthetic Data Detail View (Samples {start_idx}-{end_idx})', fontweight='bold')
    ax2.set_xlabel('Time Index')
    ax2.set_ylabel('Power (normalized)')
    ax2.grid(True, alpha=0.3)
    
    # ===== Chart 3: Power Distribution Histogram =====
    ax3 = axes[1, 0]
    
    if real_data is not None:
        ax3.hist(fake_flat, bins=50, alpha=0.6, color='blue', 
                label='Synthetic Data', density=True)
        ax3.hist(real_data, bins=50, alpha=0.6, color='red', 
                label='Real Data', density=True)
        ax3.set_title('Power Distribution Comparison', fontweight='bold')
    else:
        ax3.hist(fake_flat, bins=50, alpha=0.7, color='blue')
        ax3.set_title('Synthetic Data Power Distribution', fontweight='bold')
    
    ax3.set_xlabel('Power Value')
    ax3.set_ylabel('Density')
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    # ===== Chart 4: Statistical Information Table =====
    ax4 = axes[1, 1]
    ax4.axis('off')
    
    # Calculate statistics
    stats_data = []
    stats_data.append(['Metric', 'Synthetic Data', 'Real Data' if real_data is not None else 'N/A'])
    stats_data.append(['Sample Count', f'{len(fake_flat):,}', 
                      f'{len(real_data):,}' if real_data is not None else 'N/A'])
    stats_data.append(['Min Value', f'{fake_flat.min():.4f}', 
                      f'{real_data.min():.4f}' if real_data is not None else 'N/A'])
    stats_data.append(['Max Value', f'{fake_flat.max():.4f}', 
                      f'{real_data.max():.4f}' if real_data is not None else 'N/A'])
    stats_data.append(['Mean', f'{fake_flat.mean():.4f}', 
                      f'{real_data.mean():.4f}' if real_data is not None else 'N/A'])
    stats_data.append(['Std Dev', f'{fake_flat.std():.4f}', 
                      f'{real_data.std():.4f}' if real_data is not None else 'N/A'])
    
    # Create table
    table = ax4.table(cellText=stats_data, loc='center', cellLoc='center',
                     colWidths=[0.3, 0.35, 0.35])
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 2)
    
    # Beautify table
    for i in range(len(stats_data)):
        if i == 0:  # Header row
            for j in range(3):
                table[(i, j)].set_facecolor('#4CAF50')
                table[(i, j)].set_text_props(weight='bold', color='white')
        else:
            table[(i, 0)].set_facecolor('#E8F5E9')
    
    ax4.set_title('Statistical Comparison', fontweight='bold', pad=20)
    
    plt.tight_layout()
    
    # Save figure
    output_dir = 'OUTPUT/visualizations'
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, f'{appliance_name}_visualization.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"\nVisualization saved: {output_path}")
    
    plt.show()

def main():
    parser = argparse.ArgumentParser(description='Visualize synthetic data generated by diffusion model')
    parser.add_argument('--appliance', type=str, default='washingmachine',
                       choices=['kettle', 'microwave', 'fridge', 'dishwasher', 'washingmachine'],
                       help='Appliance name')
    
    args = parser.parse_args()
    appliance_name = args.appliance
    
    print("=" * 60)
    print(f"Visualizing Synthetic Data: {appliance_name.upper()}")
    print("=" * 60)
    
    # Load data
    fake_data = load_synthetic_data(appliance_name)
    if fake_data is None:
        return
    
    real_data = load_real_data(appliance_name)
    
    print("\nGenerating visualization...")
    
    # Plot
    plot_visualization(fake_data, real_data, appliance_name)
    
    print("\nVisualization completed!")
    print("=" * 60)

if __name__ == '__main__':
    main()
